# Site settings
title: Rapid Manufacturing Lab
description: > # this means to ignore newlines until "baseurl:"
 
 &copy RM Lab. All rights reserved <br> 
 IIT Bombay,<br/>
       Powai, Mumbai - 400076<br/>
       022 2576 7530 | rmlab.me.iitb@gmail.com <br/>
 Website created by Neel Kamal Gupta
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://neelkamalgupta.github.io" # the base hostname & protocol for your site
# twitter_username: Rishabh Arya

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
# http://svmiller.com
